package com.qf.lxsdsdsa;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.qf.lxsdsdsa.UserEntity;
import com.qf.lxsdsdsa.FruitEntity;

import com.qf.lxsdsdsa.UserEntityDao;
import com.qf.lxsdsdsa.FruitEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userEntityDaoConfig;
    private final DaoConfig fruitEntityDaoConfig;

    private final UserEntityDao userEntityDao;
    private final FruitEntityDao fruitEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userEntityDaoConfig = daoConfigMap.get(UserEntityDao.class).clone();
        userEntityDaoConfig.initIdentityScope(type);

        fruitEntityDaoConfig = daoConfigMap.get(FruitEntityDao.class).clone();
        fruitEntityDaoConfig.initIdentityScope(type);

        userEntityDao = new UserEntityDao(userEntityDaoConfig, this);
        fruitEntityDao = new FruitEntityDao(fruitEntityDaoConfig, this);

        registerDao(UserEntity.class, userEntityDao);
        registerDao(FruitEntity.class, fruitEntityDao);
    }
    
    public void clear() {
        userEntityDaoConfig.getIdentityScope().clear();
        fruitEntityDaoConfig.getIdentityScope().clear();
    }

    public UserEntityDao getUserEntityDao() {
        return userEntityDao;
    }

    public FruitEntityDao getFruitEntityDao() {
        return fruitEntityDao;
    }

}
